declare -A arr

arr+=( 
["1941"]=-2
["1943j"]=-2
["1943kai"]=-1
["1943mii"]=-1
["1943u"]=-2
["280zzzap"]=0
["3wonders"]=-1
["4dwarrio"]=-1
["jt1942"]=-2
["A.1942"]=-4
["A.ARKANOID"]=-1
["A.ASTDELUX"]=-3
["A.ASTROCADE"]=-1
["A.CCLIMB"]=-2
["A.COMSPC"]=-1
["A.GALAXN"]=-1
["A.PACMAN"]=-3
["alibaba"]=-2
["alienaru"]=-4
["amidars"]=0
["anteater"]=-1
["ares"]=0
["arkanoid"]=-1
["arkanoidj"]=-1
["arkanoiduo"]=-1
["armorcar"]=0
["asteroid"]=-2
["atetris"]=0
["atetrisc"]=0
["atlantis2"]=0
["attackfc"]=-2
["azurian"]=0
["bagman"]=0
["ballbomb"]=0
["battroad"]=-1
["beastfp"]=-1
["berzerk"]=0
["bigkong"]=-2
["bionicc"]=-2
["birdiy"]=-2
["blkhole"]=-1
["blktiger"]=-2
["blockgal"]=0
["blueshrk"]=0
["bombjack"]=0
["boothill"]=-1
["botanic"]=-2
["breakout"]=0
["brubber"]=0
["btime"]=-1
["bubblbobl"]=0
["bubbles"]=-4
["bullfgt"]=0
["bwidow"]=-2
["calipso"]=-1
["canyon"]=-2
["captcomm"]=-2
["catacomb"]=-1
["cavenger"]=-3
["cawing"]=-3
["centiped"]=-1
["ckongo"]=-2
["ckongpt2"]=-2
["Clean Sweep"]=0
["clowns"]=0
["clubpacm"]=-3
["colony7"]=-1
["commando"]=-2
["contrae"]=-1
["cosmo"]=-3
["crater"]=-1
["crbaloon"]=-2
["crush2"]=-3
["cworld2j"]=-2
["daimakair"]=-1
["darkplnt"]=-1
["ddonpach"]=-1
["ddragon"]=-1
["ddragon2"]=0
["defender"]=-4
["demoderm"]=-2
["devilfsg"]=-1
["digdug"]=-2
["digdug2"]=-1
["dino"]=-1
["dkong"]=0
["dkongjr"]=-3
["domino"]=0
["dominos"]=0
["dorodon"]=-3
["dotron"]=0
["dremshpr"]=-3
["dynwar"]=-1
["ebases"]=-3
["eeekkp"]=-2
["eggor"]=-3
["eyes"]=-2
["f1dream"]=-2
["ffight"]=-2
["flicky"]=0
["foodf"]=0
["forgottn"]=-1
["frenzy"]=0
["frogger"]=0
["frogger"]=0
["galaga3"]=-1
["galagamw"]=0
["galaxian"]=-1
["galxwars"]=-2
["ganbare"]=-1
["gaplus"]=-1
["gaunt2"]=0
["gauntlet"]=0
["gauntlet2pr3"]=0
["gberet"]=-2
["gemini"]=-2
["ghouls"]=0
["gng"]=-1
["gng"]=-1
["gorkans"]=-3
["gravitar"]=-1
["gulunpa"]=0
["gunfight"]=-3
["gunsmoke"]=-2
["gyruss"]=-1
["gyrussb"]=-1
["gyrussce"]=-1
["higemaru"]=-3
["horizon"]=-2
["imsorry"]=-1
["invad2ct"]=-3
["invaders"]=-3
["invadpt2"]=-3
["jin"]=-3
["journey"]=-1
["joust"]=-4
["jumpshot"]=-1
["kick"]=0
["kickman"]=0
["kidniki"]=-1
["knights"]=0
["kod"]=-1
["kroozr"]=0
["kungfum"]=-2
["ladybug"]=-3
["lagunar"]=-1
["ldrun"]=-1
["ldrun2"]=-2
["ldrun3"]=-2
["ldrun4"]=-2
["lizwiz"]=-2
["llander"]=-3
["losttomb"]=-1
["lrescue"]=-4
["luctoday"]=0
["lunarbattle"]=0
["lupin3a"]=-2
["lwings"]=-2
["makaimur"]=-2
["mappy"]=-1
["mario"]=-2
["mars"]=-1
["maxrpm"]=-3
["mayday"]=-4
["maze"]=0
["mbombrd"]=0
["megaman"]=0
["mercs"]=-2
["mimonscre"]=-1
["minefld"]=0
["mooncrgx"]=-1
["moonwar"]=-2
["motos"]=-1
["mpatrol"]=-1
["mrgoemon"]=-2
["mrtnt"]=-2
["mrviking"]=-1
["mspacman"]=-2
["msword"]=-2
["mtwins"]=-2
["myhero"]=0
["nemo"]=-1
["ninjakun"]=-1
["nrallyx"]=-1
["omega"]=-1
["orbitron"]=-1
["pacman"]=-3
["pacplus"]=-3
["pang3"]=0
["pengo"]=-1
["phoenix"]=-2
["pickin"]=-2
["pisces"]=-1
["pitfall2"]=0
["pitfall2u"]=0
["pkunwar"]=0
["pkunwarj"]=0
["playball"]=-2
["pleiadce"]=-3
["pleiads"]=-2
["pnickj"]=0
["pnpoko"]=-2
["pokonyan"]=-1
["pong"]=0
["pooyan"]=0
["popeye"]=-2
["powerdrv"]=-1
["puckman"]=-3
["puckmanb"]=-3
["punisher"]=0
["qad"]=0
["qtono2j"]=0
["raflesia"]=-1
["rallyx"]=0
["rampage"]=-1
["regulus"]=-1
["rescue"]=0
["robby"]=-2
["robotron"]=-5
["rpatroln"]=-1
["rushatck"]=-2
["rygar"]=-1
["sarge"]=-2
["sbagman"]=0
["sbrkout"]=-2
["schaser"]=-4
["scobra"]=0
["scramble"]=0
["seawolf"]=-2
["seawolf2"]=0
["sectionz"]=-2
["seganinj"]=0
["sf"]=-2
["sf2"]=-1
["sf2ce"]=-1
["sf2hf"]=-1
["sfzch"]=-1
["shollow"]=-1
["shtrider"]=0
["shuffle"]=-2
["shuttlei"]=-2
["sidearms"]=-2
["silkwrm"]=-1
["silvland"]=-2
["sinistar"]=-3
["skyskipr"]=-3
["slammst"]=0
["snapjack"]=-3
["solarfox"]=-2
["solomon"]=0
["solomonj"]=0
["spacezap"]=-3
["spatter"]=-1
["spcenctr"]=-4
["spdcoin"]=0
["spelunk2"]=-1
["spelunkr"]=-1
["splat"]=-4
["sprglbpg"]=-2
["sprint1"]=-1
["sprint2"]=-2
["spyhunt"]=0
["squaitsa"]=0
["stargate"]=-5
["stargrds"]=-2
["starjack"]=0
["starjacks"]=0
["stratgyx"]=0
["strider"]=-1
["swat"]=0
["szaxxon"]=-2
["tapper"]=-2
["tazmania"]=0
["teddybb"]=0
["theend"]=-2
["theglobp"]=-2
["tigerroad"]=-2
["timber"]=-1
["timeplt"]=0
["todruaga"]=-1
["tokiob"]=-3
["tp84"]=-2
["tp84a"]=-2
["tp84b"]=-2
["travrusa"]=0
["trojanr"]=-2
["tron"]=-1
["turbotag"]=-2
["turtles"]=0
["twotigerc"]=-2
["ultratnk"]=0
["uniwars"]=-1
["unsquad"]=-1
["upndown"]=0
["vanvan"]=-1
["varth"]=-1
["venus"]=-1
["victorycb"]=-1
["vindctr2"]=-1
["vortex"]=-4
["vulgus"]=-3
["wacko"]=-3
["warofbug"]=0
["wboy"]=-1
["willow"]=-1
["wmatch"]=0
["wof"]=-1
["woodpeck"]=-3
["wow"]=-1
["xevious"]=-1
["youjyudn"]=-2
["zaxxon"]=-2
["zigzagb"]=-2
["Astrocade"]=-2
["Atari2600"]=-3
["Atari5200"]=-2
["AY-3-8500"]=-1
["C2650"]=0
["Coleco"]=0
["Gameboy"]=-2
["GBA"]=0
["Genesis"]=-1
["MegaCD"]=0
["NeoGeo"]=-2
["NES"]=-1
["Odyssey2"]=-1
["SMS"]=0
["SNES"]=0
["TGFX16"]=0
["Vectrex"]=0
)

outputDir="/media/fat/config"

for key in "${!arr[@]}"; do    

    value=${arr[${key}]};    
    cfgFileName="${outputDir}/${key}_volume.CFG";

    case $value in

        0)
        echo "\c" > "$cfgFileName";
        ;;
        -1)
        echo -e "\0001\c" > "$cfgFileName";
        ;;
        -2)
        echo -e "\0002\c" > "$cfgFileName";
        ;;
        -3)
        echo -e "\0003\c" > "$cfgFileName";
        ;;
        -4)
        echo -e "\0004\c" > "$cfgFileName";
        ;;
        -5)
        echo -e "\0005\c" > "$cfgFileName";
        ;;
        -6)
        echo -e "\0006\c" > "$cfgFileName";
        ;;
    *)
    esac

done

echo "Please set TurboGrafx16 core Master audio to 2X"
