declare -A arr

arr+=( 
["1941"]=-3
["1943j"]=-3
["1943kai"]=-2
["1943mii"]=-2
["1943u"]=-3
["280zzzap"]=-1
["3wonders"]=-2
["4dwarrio"]=-2
["jt1942"]=-3
["A.1942"]=-5
["A.ARKANOID"]=-2
["A.ASTDELUX"]=-4
["A.ASTROCADE"]=-2
["A.CCLIMB"]=-3
["A.COMSPC"]=-2
["A.GALAXN"]=-2
["A.PACMAN"]=-4
["alibaba"]=-3
["alienaru"]=-5
["amidars"]=-1
["anteater"]=-2
["ares"]=-1
["arkanoid"]=-2
["arkanoidj"]=-2
["arkanoiduo"]=-2
["armorcar"]=-1
["asteroid"]=-3
["atetris"]=-1
["atetrisc"]=-1
["atlantis2"]=-1
["attackfc"]=-3
["azurian"]=-1
["bagman"]=-1
["ballbomb"]=-1
["battroad"]=-2
["beastfp"]=-2
["berzerk"]=-1
["bigkong"]=-3
["bionicc"]=-3
["birdiy"]=-3
["blkhole"]=-2
["blktiger"]=-3
["blockgal"]=-1
["blueshrk"]=-1
["bombjack"]=-1
["boothill"]=-2
["botanic"]=-3
["breakout"]=-1
["brubber"]=-1
["btime"]=-2
["bubblbobl"]=-1
["bubbles"]=-5
["bullfgt"]=-1
["bwidow"]=-3
["calipso"]=-2
["canyon"]=-3
["captcomm"]=-3
["catacomb"]=-2
["cavenger"]=-4
["cawing"]=-4
["centiped"]=-2
["ckongo"]=-3
["ckongpt2"]=-3
["Clean Sweep"]=-1
["clowns"]=-1
["clubpacm"]=-4
["colony7"]=-2
["commando"]=-3
["contrae"]=-2
["cosmo"]=-4
["crater"]=-2
["crbaloon"]=-3
["crush2"]=-4
["cworld2j"]=-3
["daimakair"]=-2
["darkplnt"]=-2
["ddonpach"]=-2
["ddragon"]=-2
["ddragon2"]=-1
["defender"]=-5
["demoderm"]=-3
["devilfsg"]=-2
["digdug"]=-3
["digdug2"]=-2
["dino"]=-2
["dkong"]=-1
["dkongjr"]=-4
["domino"]=-1
["dominos"]=-1
["dorodon"]=-4
["dotron"]=-1
["dremshpr"]=-4
["dynwar"]=-2
["ebases"]=-4
["eeekkp"]=-3
["eggor"]=-4
["eyes"]=-3
["f1dream"]=-3
["ffight"]=-3
["flicky"]=-1
["foodf"]=-1
["forgottn"]=-2
["frenzy"]=-1
["frogger"]=-1
["frogger"]=-1
["galaga3"]=-2
["galagamw"]=-1
["galaxian"]=-2
["galxwars"]=-3
["ganbare"]=-2
["gaplus"]=-2
["gaunt2"]=-1
["gauntlet"]=-1
["gauntlet2pr3"]=-1
["gberet"]=-3
["gemini"]=-3
["ghouls"]=-1
["gng"]=-2
["gng"]=-2
["gorkans"]=-4
["gravitar"]=-2
["gulunpa"]=-1
["gunfight"]=-4
["gunsmoke"]=-3
["gyruss"]=-2
["gyrussb"]=-2
["gyrussce"]=-2
["higemaru"]=-4
["horizon"]=-3
["imsorry"]=-2
["invad2ct"]=-4
["invaders"]=-4
["invadpt2"]=-4
["jin"]=-4
["journey"]=-2
["joust"]=-5
["jumpshot"]=-2
["kick"]=-1
["kickman"]=-1
["kidniki"]=-2
["knights"]=-1
["kod"]=-2
["kroozr"]=-1
["kungfum"]=-3
["ladybug"]=-4
["lagunar"]=-2
["ldrun"]=-2
["ldrun2"]=-3
["ldrun3"]=-3
["ldrun4"]=-3
["lizwiz"]=-3
["llander"]=-4
["losttomb"]=-2
["lrescue"]=-5
["luctoday"]=-1
["lunarbattle"]=-1
["lupin3a"]=-3
["lwings"]=-3
["makaimur"]=-3
["mappy"]=-2
["mario"]=-3
["mars"]=-2
["maxrpm"]=-4
["mayday"]=-5
["maze"]=-1
["mbombrd"]=-1
["megaman"]=-1
["mercs"]=-3
["mimonscre"]=-2
["minefld"]=-1
["mooncrgx"]=-2
["moonwar"]=-3
["motos"]=-2
["mpatrol"]=-2
["mrgoemon"]=-3
["mrtnt"]=-3
["mrviking"]=-2
["mspacman"]=-3
["msword"]=-3
["mtwins"]=-3
["myhero"]=-1
["nemo"]=-2
["ninjakun"]=-2
["nrallyx"]=-2
["omega"]=-2
["orbitron"]=-2
["pacman"]=-4
["pacplus"]=-4
["pang3"]=-1
["pengo"]=-2
["phoenix"]=-3
["pickin"]=-3
["pisces"]=-2
["pitfall2"]=-1
["pitfall2u"]=-1
["pkunwar"]=-1
["pkunwarj"]=-1
["playball"]=-3
["pleiadce"]=-4
["pleiads"]=-3
["pnickj"]=-1
["pnpoko"]=-3
["pokonyan"]=-2
["pong"]=-1
["pooyan"]=-1
["popeye"]=-3
["powerdrv"]=-2
["puckman"]=-4
["puckmanb"]=-4
["punisher"]=-1
["qad"]=-1
["qtono2j"]=-1
["raflesia"]=-2
["rallyx"]=-1
["rampage"]=-2
["regulus"]=-2
["rescue"]=-1
["robby"]=-3
["robotron"]=-6
["rpatroln"]=-2
["rushatck"]=-3
["rygar"]=-2
["sarge"]=-3
["sbagman"]=-1
["sbrkout"]=-3
["schaser"]=-5
["scobra"]=-1
["scramble"]=-1
["seawolf"]=-3
["seawolf2"]=-1
["sectionz"]=-3
["seganinj"]=-1
["sf"]=-3
["sf2"]=-2
["sf2ce"]=-2
["sf2hf"]=-2
["sfzch"]=-2
["shollow"]=-2
["shtrider"]=-1
["shuffle"]=-3
["shuttlei"]=-3
["sidearms"]=-3
["silkwrm"]=-2
["silvland"]=-3
["sinistar"]=-4
["skyskipr"]=-4
["slammst"]=-1
["snapjack"]=-4
["solarfox"]=-3
["solomon"]=-1
["solomonj"]=-1
["spacezap"]=-4
["spatter"]=-2
["spcenctr"]=-5
["spdcoin"]=-1
["spelunk2"]=-2
["spelunkr"]=-2
["splat"]=-5
["sprglbpg"]=-3
["sprint1"]=-2
["sprint2"]=-3
["spyhunt"]=-1
["squaitsa"]=-1
["stargate"]=-6
["stargrds"]=-3
["starjack"]=-1
["starjacks"]=-1
["stratgyx"]=-1
["strider"]=-2
["swat"]=-1
["szaxxon"]=-3
["tapper"]=-3
["tazmania"]=-1
["teddybb"]=-1
["theend"]=-3
["theglobp"]=-3
["tigerroad"]=-3
["timber"]=-2
["timeplt"]=-1
["todruaga"]=-2
["tokiob"]=-4
["tp84"]=-3
["tp84a"]=-3
["tp84b"]=-3
["travrusa"]=-1
["trojanr"]=-3
["tron"]=-2
["turbotag"]=-3
["turtles"]=-1
["twotigerc"]=-3
["ultratnk"]=-1
["uniwars"]=-2
["unsquad"]=-2
["upndown"]=-1
["vanvan"]=-2
["varth"]=-2
["venus"]=-2
["victorycb"]=-2
["vindctr2"]=-2
["vortex"]=-5
["vulgus"]=-4
["wacko"]=-4
["warofbug"]=-1
["wboy"]=-2
["willow"]=-2
["wmatch"]=-1
["wof"]=-2
["woodpeck"]=-4
["wow"]=-2
["xevious"]=-2
["youjyudn"]=-3
["zaxxon"]=-3
["zigzagb"]=-3
["Astrocade"]=-3
["Atari2600"]=-4
["Atari5200"]=-3
["AY-3-8500"]=-2
["C2650"]=-1
["Coleco"]=0
["Gameboy"]=-3
["GBA"]=-1
["Genesis"]=-2
["MegaCD"]=-1
["NeoGeo"]=-3
["NES"]=-2
["Odyssey2"]=-2
["SMS"]=-1
["SNES"]=-1
["TGFX16"]=-1
["Vectrex"]=-1
)

outputDir="/media/fat/config"

for key in "${!arr[@]}"; do    

    value=${arr[${key}]};    
    cfgFileName="${outputDir}/${key}_volume.CFG";

    case $value in

        0)
        echo "\c" > "$cfgFileName";
        ;;
        -1)
        echo -e "\0001\c" > "$cfgFileName";
        ;;
        -2)
        echo -e "\0002\c" > "$cfgFileName";
        ;;
        -3)
        echo -e "\0003\c" > "$cfgFileName";
        ;;
        -4)
        echo -e "\0004\c" > "$cfgFileName";
        ;;
        -5)
        echo -e "\0005\c" > "$cfgFileName";
        ;;
        -6)
        echo -e "\0006\c" > "$cfgFileName";
        ;;
    *)
    esac

done

echo "Audio normalization complete. Thanks for playing. Please come again."